### PR TITLE
Fix some lint issues and add `npm run build` for UMD module

### PR DESCRIPTION
**Pull request by jotto**
This PR began as a couple of lint fixes so I could copy and paste the minified code into an existing project without blowing up eslint.

Then, it seemed easy enough to just create a UMD module definition. All that's left now is to push to the npm registry.

There are no tests to run, but I verified most functionality works as a browser global and require/import.

* Usage in the browser doesn't change.
* `import 'amazon-cognito-js';` or `require('amazon-cognito-js');` (after they push to npmjs.org)
* to build, instead of `grunt uglify`, do `npm run build` (same command as [amazon-cognito-identity-js](https://github.com/aws/amazon-cognito-identity-js/blob/454608e98662c21b9f84553e1c7fc6f19ad40be0/package.json#L33))

### CODE REVIEW

**Comment by itrestian** [comment]
Thanks @jotto! I will bring up the pull request within the team in order to merge it. Weird that the callback in removeRecord was called in the body but not present in the function signature .

**Comment by jotto** [comment]
gentle ping

**Comment by itrestian** [comment]
Hi, can you confirm that we can use, modify, copy, and redistribute this PR? Thank you!

**Comment by jotto** [comment]
> Hi, can you confirm that we can use, modify, copy, and redistribute this PR? Thank you!

I confirm that this PR can be used, modified, copied, and redistributed.

**Pull request merged**
