### PR TITLE
Slice the request objects before before shifting them out of the orig…

### PR DESCRIPTION
**Pull request by NuclearCookie**
…inal array.

The request object is required by code that is called after the code that shifts all items from the array.
This caused a bug in the sync code, where the lastSyncCount was not set, causing the system to think that there were changes on the remote while there were not.

Note: This is a major bug. It should be merged in asap.

### CODE REVIEW

**Comment by NuclearCookie** [comment]
I've resolved the merge conflict ( in the dist file of course ) so it's ready to be accepted. Please take a look at it. It's an important bug.

**Comment by NuclearCookie** [comment]
@itrestian I'm really disappointed in the support and activity for this project. I would have expected a big company like Amazon to at least take a look at pull requests and sort them based on priority or whatever. Just something so we at least see you don't ignore whoever is willing to help you.

**Comment by itrestian** [comment]
@NuclearCookie Sorry for the delay. LGTM. Merged your pull request.

**Comment by NuclearCookie** [comment]
Thanks for the reply!

**Comment by itrestian** [comment]
Also, can you confirm that we can use, modify, copy, and redistribute this PR? Thanks!

**Comment by NuclearCookie** [comment]
Yes you surely can.

**Pull request merged**
